[package]
name = "leetcode-utils-rs"
version = "0.0.1"
authors = ["Katsuki Kobayashi <rare@tirasweel.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
